import requests

class CurrencyAPI:
  def __init__(self, currency = 'usd'):
    '''
    sets up currency api class
    args: self: current instance 
          currency: desired currency 
    return: (str) desired currency
    '''
    self.currency = currency
    self.api_url = f'https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/usd/{currency}.json'
  
  def get(self):
    '''
    returns exchange rate to US dollars
    args: self: current instance
    return: (float) exchange rate to US dollars
    '''
    r = requests.get(self.api_url)
    response = r.json()
    
    if response[self.currency]:
      return response[self.currency]
    else:
      return None

  def print_supported_currency():
    '''
    prints list of supported currency and their corresponding IDs
    args: None
    returns: None
    '''
    print("These are the currently supported currencies:\n")
    print("Currency:                                      ID:\n")
    print("\n1inch Network                                1inch")
    print("\nAave                                          aave")
    print("\nCardano                                        ada")
    print("\nUnited Arab Emirates Dirham                    aed")
    print("\nAfghan afghani                                 afn")
    print("\nAlgorand                                      algo")
    print("\nAlbanian lek                                   all")
    print("\nArmenian dram                                  amd")
    print("\nSynereo                                        amp")
    print("\nNetherlands Antillean Guilder                  ang")
    print("\nAngolan kwanza                                 aoa")
    print("\nArweave                                         ar")
    print("\nArgentine peso                                 ars")
    print("\nAtomic Coin                                   atom")
    print("\nAustralian dollar                              aud")
    print("\nAvalanche                                     avax")
    print("\nAruban florin                                  awg")
    print("\nAXS                                            axs")
    print("\nAzerbaijani manat                              azn")
    print("\nBosnia-Herzegovina Convertible Mark            bam")
    print("\nBasic Attention Token                          bat")
    print("\nBajan dollar                                   bbd")
    print("\nBitcoin Cash                                   bch")
    print("\nBangladeshi taka                               bdt")
    print("\nBulgarian lev                                  bgn")
    print("\nBahraini dinar                                 bhd")
    print("\nBurundian Franc                                bif")
    print("\nBermudan dollar                                bmd")
    print("\nBinance Coin                                   bnb")
    print("\nBrunei dollar                                  bnd")
    print("\nBolivian boliviano                             bob")
    print("\nBrazilian real                                 brl")
    print("\nBahamian dollar                                bsd")
    print("\nBitcoin SV                                     bsv")
    print("\nBiswap                                         bsw")
    print("\nBitcoin                                        btc")
    print("\nBitcoin BEP2                                  btcb")
    print("\nBitcoin Gold                                   btg")
    print("\nBhutan currency                                btn")
    print("\nBinance USD                                   busd")
    print("\nBotswanan Pula                                 bwp")
    print("\nNew Belarusian Ruble                           byn")
    print("\nBelarusian Ruble                               byr")
    print("\nBelize dollar                                  bzd")
    print("\nCanadian dollar                                cad")
    print("\nPancakeSwap                                   cake")
    print("\nCongolese franc                                cdf")
    print("\nCelo                                          celo")
    print("\nSwiss franc                                    chf")
    print("\nChiliz                                         chz")
    print("\nChilean Unit of Account (UF)                   clf")
    print("\nChilean peso                                   clp")
    print("\nChinese Yuan                                   cny")
    print("\nCompound Coin                                 comp")
    print("\nColombian peso                                 cop")
    print("\nCosta Rican Colón                              crc")
    print("\nCrypto.com Chain Token                         cro")
    print("\nCravy                                          crv")
    print("\nCuban peso                                     cuc")
    print("\nCuban Peso                                     cup")
    print("\nCape Verdean escudo                            cve")
    print("\nConvex Finance                                 cvx")
    print("\nCzech koruna                                   czk")
    print("\nDai                                            dai")
    print("\nDash                                          dash")
    print("\nDecred                                         dcr")
    print("\nDfiStarter                                     dfi")
    print("\nDjiboutian franc                               djf")
    print("\nDanish krone                                   dkk")
    print("\nDogecoin                                      doge")
    print("\nDominican peso                                 dop")
    print("\nDotcoin                                        dot")
    print("\nAlgerian dinar                                 dzd")
    print("\nElrond                                        egld")
    print("\nEgyptian pound                                 egp")
    print("\nEnjin Coin                                     enj")
    print("\nEOS                                            eos")
    print("\nEritrean nakfa                                 ern")
    print("\nEthiopian birr                                 etb")
    print("\nEthereum Classic                               etc")
    print("\nEther                                          eth")
    print("\nEuro                                           eur")
    print("\nFei USD                                        fei")
    print("\nFileCoin                                       fil")
    print("\nFijian dollar                                  fjd")
    print("\nFalkland Islands pound                         fkp")
    print("\nFlow                                          flow")
    print("\nFrax                                          frax")
    print("\nFantom                                         ftm")
    print("\nFarmaTrust                                     ftt")
    print("\nGala                                          gala")
    print("\nPound sterling                                 gbp")
    print("\nGeorgian lari                                  gel")
    print("\nGGPro                                          ggp")
    print("\nGhanaian cedi                                  ghs")
    print("\nGibraltar pound                                gip")
    print("\nGambian dalasi                                 gmd")
    print("\nGuinean franc                                  gnf")
    print("\nGnosis                                         gno")
    print("\nGolden Ratio Token                             grt")
    print("\nGateToken                                       gt")
    print("\nGuatemalan quetzal                             gtq")
    print("\nGuyanaese Dollar                               gyd")
    print("\nHedera                                        hbar")
    print("\nHong Kong dollar                               hkd")
    print("\nHonduran lempira                               hnl")
    print("\nHelium                                         hnt")
    print("\nHydro Protocol                                 hot")
    print("\nCroatian kuna                                  hrk")
    print("\nHuobi Token                                     ht")
    print("\nHaitian gourde                                 htg")
    print("\nHungarian forint                               huf")
    print("\nInternet Computer                              icp")
    print("\nIndonesian rupiah                              idr")
    print("\nIsraeli New Shekel                             ils")
    print("\nCoinIMP                                        imp")
    print("\nInjective                                      inj")
    print("\nIndian rupee                                   inr")
    print("\nIraqi dinar                                    iqd")
    print("\nIranian rial                                   irr")
    print("\nIcelandic króna                                isk")
    print("\nJersey Pound                                   jep")
    print("\nJamaican dollar                                jmd")
    print("\nJordanian dinar                                jod")
    print("\nJapanese yen                                   jpy")
    print("\nKava                                          kava")
    print("\nKucoin                                         kcs")
    print("\nKadena                                         kda")
    print("\nKenyan shilling                                kes")
    print("\nKyrgystani Som                                 kgs")
    print("\nCambodian riel                                 khr")
    print("\nKlaytn                                        klay")
    print("\nComorian franc                                 kmf")
    print("\nKyber Network                                  knc")
    print("\nNorth Korean won                               kpw")
    print("\nSouth Korean won                               krw")
    print("\nKusama                                         ksm")
    print("\nKuwaiti dinar                                  kwd")
    print("\nCayman Islands dollar                          kyd")
    print("\nKazakhstani tenge                              kzt")
    print("\nLaotian Kip                                    lak")
    print("\nLebanese pound                                 lbp")
    print("\nLEOcoin                                        leo")
    print("\nChainLink                                     link")
    print("\nSri Lankan rupee                               lkr")
    print("\nLoopring                                       lrc")
    print("\nLiberian dollar                                lrd")
    print("\nLesotho loti                                   lsl")
    print("\nLitecoin                                       ltc")
    print("\nLithuanian litas                               ltl")
    print("\nLuna Coin                                     luna")
    print("\nLatvian lats                                   lvl")
    print("\nLibyan dinar                                   lyd")
    print("\nMoroccan dirham                                mad")
    print("\nDecentraland                                  mana")
    print("\nPolygon                                      matic")
    print("\nMoldovan leu                                   mdl")
    print("\nMalagasy ariary                                mga")
    print("\nMina                                          mina")
    print("\nIOTA                                         miota")
    print("\nMacedonian denar                               mkd")
    print("\nMaker                                          mkr")
    print("\nMyanmar Kyat                                   mmk")
    print("\nMongolian tugrik                               mnt")
    print("\nMacanese pataca                                mop")
    print("\nMauritanian ouguiya                            mro")
    print("\nMauritian rupee                                mur")
    print("\nMaldivian rufiyaa                              mvr")
    print("\nMalawian kwacha                                mwk")
    print("\nMexican peso                                   mxn")
    print("\nMalaysian ringgit                              myr")
    print("\nMozambican Metical                             mzn")
    print("\nNamibian dollar                                nad")
    print("\nNEAR Protocol                                 near")
    print("\nNEO                                            neo")
    print("\nNEXO                                          nexo")
    print("\nNigerian naira                                 ngn")
    print("\nNicaraguan córdoba                             nio")
    print("\nNorwegian krone                                nok")
    print("\nNepalese rupee                                 npr")
    print("\nNew Zealand dollar                             nzd")
    print("\nOkex                                           okb")
    print("\nOmani rial                                     omr")
    print("\nMenlo One                                      one")
    print("\nPanamanian balboa                              pab")
    print("\nPAX Gold                                      paxg")
    print("\nSol                                            pen")
    print("\nPapua New Guinean kina                         pgk")
    print("\nPhilippine peso                                php")
    print("\nPakistani rupee                                pkr")
    print("\nPoland złoty                                   pln")
    print("\nParaguayan guarani                             pyg")
    print("\nQatari Rial                                    qar")
    print("\nQuant                                          qnt")
    print("\nQTUM                                          qtum")
    print("\nRomanian leu                                   ron")
    print("\nSerbian dinar                                  rsd")
    print("\nRussian ruble                                  rub")
    print("\nTHORChain (ERC20)                             rune")
    print("\nRwandan Franc                                  rwf")
    print("\nBeachCoin                                     sand")
    print("\nSaudi riyal                                    sar")
    print("\nSolomon Islands dollar                         sbd")
    print("\nSeychellois rupee                              scr")
    print("\nSudanese pound                                 sdg")
    print("\nSwedish krona                                  sek")
    print("\nSingapore dollar                               sgd")
    print("\nShiba Inu                                     shib")
    print("\nSaint Helena pound                             shp")
    print("\n                                               sle")
    print("\nSierra Leonean leone                           sll")
    print("\nSola                                           sol")
    print("\nSomali shilling                                sos")
    print("\nSurinamese dollar                              srd")
    print("\nSão Tomé and Príncipe Dobra (pre-2018)         std")
    print("\nStox                                           stx")
    print("\nSalvadoran Colón                               svc")
    print("\nSyrian pound                                   syp")
    print("\nSwazi lilangeni                                szl")
    print("\nThai baht                                      thb")
    print("\nTheta                                        theta")
    print("\nTajikistani somoni                             tjs")
    print("\nTurkmenistani manat                            tmt")
    print("\nTunisian dinar                                 tnd")
    print("\nTongan Paʻanga                                 top")
    print("\nTRON                                           trx")
    print("\nTurkish lira                                   try")
    print("\nTrinidad & Tobago Dollar                       ttd")
    print("\nTap Project                                    ttt")
    print("\nTrue USD                                      tusd")
    print("\nNew Taiwan dollar                              twd")
    print("\nTanzanian shilling                             tzs")
    print("\nUkrainian hryvnia                              uah")
    print("\nUgandan shilling                               ugx")
    print("\nUniverse                                       uni")
    print("\nUnited States dollar                           usd")
    print("\nUSD Coin                                      usdc")
    print("\nUSDP Stablecoin                               usdp")
    print("\nTether                                        usdt")
    print("\nUruguayan peso                                 uyu")
    print("\nUzbekistani som                                uzs")
    print("\nSovereign Bolivar                              vef")
    print("\n                                               ves")
    print("\nVechain                                        vet")
    print("\nVietnamese dong                                vnd")
    print("\nVanuatu vatu                                   vuv")
    print("\nWaves                                        waves")
    print("\nWrapped Bitcoin                               wbtc")
    print("\nWEMIX                                        wemix")
    print("\nSamoan tala                                    wst")
    print("\nCentral African CFA franc                      xaf")
    print("\nSilver Ounce                                   xag")
    print("\nXauCoin                                        xau")
    print("\nEast Caribbean dollar                          xcd")
    print("\nChia                                           xch")
    print("\nXDC Network                                    xdc")
    print("\nSpecial Drawing Rights                         xdr")
    print("\nEternal Coin                                   xec")
    print("\nNEM                                            xem")
    print("\nStellar                                        xlm")
    print("\nMonero                                         xmr")
    print("\nWest African CFA franc                         xof")
    print("\nCFP franc                                      xpf")
    print("\nXRP                                            xrp")
    print("\nTezos                                          xtz")
    print("\nYemeni rial                                    yer")
    print("\nSouth African rand                             zar")
    print("\nZCash                                          zec")
    print("\nZilliqa                                        zil")
    print("\nZambian kwacha                                 zmk")
    print("\nZambian Kwacha                                 zmw")
    print("\nZimbabwean Dollar                              zwl\n\n")
  def __str__(self):
    '''
    create a string representation of the class
    args: self: current instance
    return: (str) of API url
    '''
    return self.api_url